### ISSUE TITLE
proxify requires Python '>=2, <=2.8' but the running Python is 3.7.1

### ISSUE THREAD

**Issue by mikolaje** [n1rv4n4/pyddoz#1]
I'm using python 3.7 .There was an issue while I'm typing pip install -r requirements.txt
proxify requires Python '>=2, <=2.8' but the running Python is 3.7.1

**Comment by bogdik** [comment]
i get analogy problem

**Comment by dazkarieh** [comment]
some issue,PLZ tell me how 2 fix it?

**Comment by n1rv4n4** [comment]
"**proxify**" doesn't support Python 3.7.1, so consider to use **Python 3.5.x**.

**Comment by n1rv4n4** [comment]
I'm using Python 3.5.2 without any problem, **proxify** https://pypi.org/project/proxify/ shows that it supports the list of the versions below. In future, we think to change proxify with another suitable module.

- Python :: 2 
- Python :: 2.6 
- Python :: 2.7 
- Python :: 3 
- Python :: 3.2 
- Python :: 3.3 
- Python :: 3.4

**Comment by 0x01h** [comment]
Now, **proxify** module is not a requirement and PyDDoZ is compatible with all Python 3 versions!
